### ISSUE TITLE
Role can be deprecated

### ISSUE THREAD

**Issue by ypid** [htgoebel/ansible-nullmailer#1]
Hi,

to avoid confusion now that a nullmailer role is part of DebOps core, I guess this role can be deprecated ([example](https://github.com/debops/ansible-sshkeys/pull/6)).

New role: [debops.nullmailer](https://github.com/debops/ansible-nullmailer)

**Comment by ypid-geberit** [comment]
Ping: @drybjed, @htgoebel

**Comment by drybjed** [comment]
Sounds good to me.

**Comment by ypid** [comment]
@drybjed I guess @htgoebel has seen my ping as he gave my initial comment a thumbs up. So I would say the repo can be archived and the issue can be closed.

**Comment by drybjed** [comment]
Closing this issue and archiving the repository.
